language: csharp
mono: none
dotnet: 2.1.505
script:
 - dotnet restore
 - dotnet publish -c Release -f netcoreapp2.1 --self-contained -o pub\Win64 -r win-x64 .
 - dotnet publish -c Release -f netcoreapp2.1 --self-contained -o pub\Win32 -r win-x86 .
 - dotnet publish -c Release -f netcoreapp2.1 --self-contained -o pub\Linux64 -r linux-x64 .
 - dotnet publish -c Release -f netcoreapp2.1 --self-contained -o pub\LinuxMin64 -r linux-musl-x64 .
 - dotnet publish -c Release -f netcoreapp2.1 --self-contained -o pub\OSX64 -r osx-x64 .
 - 7z a -tzip pub\Win64\
 - 7z a -tzip pub\Win32\
 - 7z a -tzip pub\Linux64\
 - 7z a -tzip pub\LinuxMin64\
 - 7z a -tzip pub\OSX64\